### PR TITLE
Fix RGB21 assets issuance by using Rgb21Types instead of CommonTypes

### LINKED ISSUE #2: Addressing type resolution in RGB21 asset issuance process
## Description

I've identified and fixed three critical bugs affecting RGB21 asset issuance (FAC, UAC, UDA):

1. **TypeAbsent Error in RGB21 Issuers**
   - **Symptom:** When issuing RGB21 assets, `TypeAbsent` errors occur: `invalid strict value not matching semantic type information: TypeAbsent(SemId(SemId(Array<32>(19ebe69d137048e1596fc1e7e950af0a64c1765f29e41224ab2d2bf4e7605c77))))`
   - **Root Cause:** RGB21 issuers (FAC, UAC, UDA) were using `CommonTypes` instead of `Rgb21Types` during asset generation, preventing proper type resolution.

2. **UnknownType Error in RGB21 Type System**
   - **Symptom:** After fixing the first issue, another error appears: `UnknownType(SemId(Array<32>(de2717351edbb73c62b42378da72bf9414d2bb92374497f2997e1240d537832a)))`
   - **Root Cause:** The `Rgb21Types::type_system` `extract` method fails to recognize `ReservedBytes<26>` used in NFT's `_reserved` field because the type wasn't defined in the `commit_verify` library's type system.

3. **Encoding Error Due to Field Order Mismatch**
   - **Symptom:** After addressing the above issues, another error appears: `bug in business logic of type system` when trying to encode struct values.
   - **Root Cause:** The `strict_write_ty` method in `strict-types/src/value/encode.rs` assumes that value and type field orders match exactly, but they can differ in practice.

## Proposed Fixes

I've implemented fixes for all three issues across the affected repositories:

1. **rgb-issuers**: Replace `CommonTypes` with `Rgb21Types` in RGB21 asset issuers (fix/rgb21-types-system branch)
2. **commit-verify**: Add support for `ReservedBytes<26>` type (fix/reserved-bytes-26-support branch)
3. **strict-types**: Modify struct encoding to match fields by name instead of position (fix/value-type-order-mismatch branch)

Each fix has been tested with FAC asset issuance.

### PR DESCRIPTION
**Pull request by will-bitlightlabs**
## Description

This PR fixes the `TypeAbsent` errors when issuing RGB21 assets (FAC, UAC, UDA). 

### Problem

When attempting to issue RGB21 assets, the system would fail with:
`invalid strict value not matching semantic type information: TypeAbsent(SemId(SemId(Array<32>(19ebe69d137048e1596fc1e7e950af0a64c1765f29e41224ab2d2bf4e7605c77))))`

### Root Cause

RGB21 issuers were using `CommonTypes` instead of `Rgb21Types` for type resolution, which prevented them from finding all required types.

### Solution

Replace `CommonTypes` with `Rgb21Types` in RGB21 asset issuers to properly resolve all dependencies.

### Related Issues

Fixes #2 (Addressing type resolution in RGB21 asset issuance process)

### Testing

Successfully tested with FAC asset issuance.

### CODE REVIEW

File: rust/src/ifaces/rgb21.rs [hunk 1]
```diff
@@ -69,7 +69,7 @@ pub fn api(codex_id: CodexId) -> Api {
         },
         destructible: tiny_bmap! {
             vname!("fractions") => DestructibleApi {
-                sem_id: types.get("RGB21.NftAllocation"),
+                sem_id: types.get("RGB21.OwnedFraction"),
```
Comment (dr-orlovsky) [inline rust/src/ifaces/rgb21.rs:72]: It should be just `Nft`

```suggestion
                sem_id: types.get("RGB21.Nft"),
```

**Comment by dr-orlovsky** [comment]
Please also update the merged PRs in `patches` section so we use `master` and `v0.12` and not custom branches

**Comment by will-bitlightlabs** [comment]
> Please also update the merged PRs in `patches` section so we use `master` and `v0.12` and not custom branches

Thank you very much. I have updated the corresponding patch dependency

**Review by dr-orlovsky — APPROVED** [review]
ACK 35e9063ceef72fe10c3aba81454f99116abe2579
